apiVersion: argoproj.io/v1alpha1
kind: Rollout
metadata:
  name: demo-app
spec:
  replicas: 10
  revisionHistoryLimit: 1
  selector:
    matchLabels:
      app: demo-app
  # template:
  #   metadata:
  #     labels:
  #       app: demo-app
  #   spec:
  #     containers:
  #       - name: webcolor
  #         image: lucasrios92/web-color:green
  #         ports:
  #           - containerPort: 80
  workloadRef:
      kind: Deployment
      name: demo-app # Substitua pelo nome do seu Deployment atual
      scaleDown: never
  strategy:
      blueGreen:
        activeService: demo-app
        autoPromotionEnabled: false




##POS MIGRATION
  # strategy:
  #   canary:
  #     steps:
  #       - setWeight: 25
  #       - pause: {}
  #       - setWeight: 50
  #       - pause: {}
  #       - setWeight: 100
  #       - pause: {}