apiVersion: argoproj.io/v1alpha1
kind: Rollout
metadata:
  name: demo-app
  labels: # <--- Adicionado/Corrigido
    app: demo-app
    argo-rollout-managed: "true"
spec:
  replicas: 3
  revisionHistoryLimit: 1
  selector:
    matchLabels:
      app: demo-app
  template:
    metadata:
      labels:
        app: demo-app
    spec:
      containers:
        - name: webcolor
          image: lucasrios92/web-color:green
          ports:
            - containerPort: 80
  # workloadRef:
  #   apiVersion: apps/v1
  #   kind: Deployment
  #   name: demo-app-deployment # Substitua pelo nome do seu Deployment atual
  #   scaleDown: onsuccess
  strategy:
      canary:
        steps:
          - setWeight: 20
          - pause: {duration: 10s}




##POS MIGRATION
  # strategy:
  #   canary:
  #     steps:
  #       - setWeight: 25
  #       - pause: {}
  #       - setWeight: 50
  #       - pause: {}
  #       - setWeight: 100
  #       - pause: {}