apiVersion: v1
kind: Service
metadata:
  name: demo-app-service
  labels: 
      app: demo-app
      argo-rollout-managed: "true"
spec:
  selector:
    app: demo-app
  type: NodePort
  ports:
    - name: demo-app
      port: 80
      targetPort: 80